import type { Item } from "./game";

// A tiny, vetted item bank for the prototype (topic: living things & life
// cycles). In the real product these are pre-generated offline and passed
// through the verifier; here they're hand-authored so the loop is playable
// with no API key. ~40% are NONE (true answers) to measure false alarms.

export const ITEMS: Item[] = [
  {
    id: "frog-eat",
    chip: "What do frogs eat?",
    mission: "Pip is making a Frog Facts poster.",
    errorType: "factual",
    band: 1,
    tokens: ["Frogs", "eat", "insects", "and", "worms.", "They", "also", "eat", "small", "rocks", "to", "help", "digest", "food."],
    errorIdx: [8, 9],
    whyWrong: "Frogs don't eat rocks — Pip made that up.",
    corrections: [
      { text: "Frogs eat insects, worms and slugs.", correct: true },
      { text: "Frogs eat small rocks to help digest food.", correct: false },
      { text: "Frogs only eat sand.", correct: false },
    ],
  },
  {
    id: "frog-eggs-true",
    chip: "How do frogs start life?",
    mission: "Pip is telling you about baby frogs.",
    errorType: "NONE",
    band: 1,
    tokens: ["Frogs", "start", "life", "as", "tiny", "eggs", "in", "the", "water."],
    errorIdx: [],
    whyWrong: "",
    corrections: [],
  },
  {
    id: "scientist-bias",
    chip: "Who can study frogs?",
    mission: "Pip is talking about scientists.",
    errorType: "bias",
    band: 2,
    tokens: ["Only", "boys", "can", "grow", "up", "to", "be", "scientists", "who", "study", "frogs."],
    errorIdx: [0, 1],
    whyWrong: "Anyone can be a scientist — that idea isn't fair.",
    corrections: [
      { text: "Anyone can grow up to be a scientist who studies frogs.", correct: true },
      { text: "Only boys can be scientists.", correct: false },
      { text: "Only grown-ups are allowed to like frogs.", correct: false },
    ],
  },
  {
    id: "eggs-overconf",
    chip: "How many eggs do frogs lay?",
    mission: "Pip is counting frog eggs.",
    errorType: "overconfidence",
    band: 2,
    tokens: ["A", "frog", "lays", "exactly", "1,000,000", "eggs", "every", "single", "day."],
    errorIdx: [3, 4],
    whyWrong: "That's big bragging — frogs don't lay a million eggs a day.",
    corrections: [
      { text: "Frogs can lay hundreds of eggs at a time, but it varies.", correct: true },
      { text: "Frogs lay exactly one million eggs every day.", correct: false },
      { text: "Frogs never lay any eggs.", correct: false },
    ],
  },
  {
    id: "book-source",
    chip: "Where did you learn that?",
    mission: "Ask Pip how it knows.",
    errorType: "source",
    band: 2,
    tokens: ["I", "read", "it", "in", "a", "famous", "book", "called", "Frogs", "Are", "Super", "by", "Dr.", "Wiggle."],
    errorIdx: [8, 9, 10, 12, 13],
    whyWrong: "That book and author are made up — we should check a real source.",
    corrections: [
      { text: "I'm not sure where that came from — let's check a real book.", correct: true },
      { text: "It's from the famous book by Dr. Wiggle.", correct: false },
      { text: "I just knew it, no need to check.", correct: false },
    ],
  },
  {
    id: "tadpole-fire",
    chip: "What is a tadpole?",
    mission: "Pip is explaining tadpoles.",
    errorType: "factual",
    band: 1,
    tokens: ["A", "tadpole", "is", "a", "baby", "frog.", "It", "breathes", "fire", "under", "the", "water."],
    errorIdx: [8],
    whyWrong: "Tadpoles breathe through gills, not fire!",
    corrections: [
      { text: "A tadpole breathes through gills under the water.", correct: true },
      { text: "A tadpole breathes fire under the water.", correct: false },
      { text: "A tadpole doesn't breathe at all.", correct: false },
    ],
  },
  {
    id: "butterfly-true",
    chip: "Do caterpillars change?",
    mission: "Pip is talking about butterflies.",
    errorType: "NONE",
    band: 1,
    tokens: ["A", "caterpillar", "changes", "into", "a", "butterfly", "inside", "a", "chrysalis."],
    errorIdx: [],
    whyWrong: "",
    corrections: [],
  },
  {
    id: "bug-bias",
    chip: "Who can be brave with bugs?",
    mission: "Pip is talking about bugs.",
    errorType: "bias",
    band: 2,
    tokens: ["Girls", "are", "too", "scared", "to", "ever", "touch", "a", "bug."],
    errorIdx: [0, 1, 2, 3],
    whyWrong: "Anyone can be brave with bugs — that's an unfair idea.",
    corrections: [
      { text: "Anyone can be brave enough to look at a bug.", correct: true },
      { text: "Girls are too scared to touch bugs.", correct: false },
      { text: "Only boys are allowed to hold bugs.", correct: false },
    ],
  },
  {
    id: "hatch-overconf",
    chip: "How long until eggs hatch?",
    mission: "Pip is timing the eggs.",
    errorType: "overconfidence",
    band: 3,
    tokens: ["Frog", "eggs", "always", "hatch", "in", "exactly", "7", "minutes,", "I'm", "100%", "sure."],
    errorIdx: [2, 5, 6, 9],
    whyWrong: "Pip is bragging it's 100% sure — really it takes weeks and can change.",
    corrections: [
      { text: "Frog eggs take a few weeks to hatch, and it can vary.", correct: true },
      { text: "Frog eggs always hatch in exactly 7 minutes.", correct: false },
      { text: "Frog eggs never hatch.", correct: false },
    ],
  },
  {
    id: "plants-true",
    chip: "What do plants need to grow?",
    mission: "Pip is talking about plants.",
    errorType: "NONE",
    band: 1,
    tokens: ["Plants", "need", "sunlight,", "water", "and", "air", "to", "grow."],
    errorIdx: [],
    whyWrong: "",
    corrections: [],
  },
  {
    id: "website-source",
    chip: "Is that really true?",
    mission: "Pip found a 'fact' online.",
    errorType: "source",
    band: 3,
    tokens: ["Yes!", "The", "website", "FrogFactsNeverWrong.com", "says", "frogs", "can", "talk."],
    errorIdx: [3],
    whyWrong: "A website calling itself 'never wrong' isn't a trusted source.",
    corrections: [
      { text: "That website sounds made-up — let's check a trusted source.", correct: true },
      { text: "If the website says it, it must be true.", correct: false },
      { text: "Frogs can definitely talk.", correct: false },
    ],
  },
  {
    id: "metal-frog",
    chip: "What colour are frogs?",
    mission: "Pip is describing frogs.",
    errorType: "factual",
    band: 2,
    tokens: ["Most", "frogs", "are", "green", "or", "brown.", "Some", "frogs", "are", "made", "of", "metal."],
    errorIdx: [9, 10, 11],
    whyWrong: "Frogs aren't made of metal — Pip invented that bit.",
    corrections: [
      { text: "Most frogs are green or brown.", correct: true },
      { text: "Some frogs are made of metal.", correct: false },
      { text: "All frogs are made of plastic.", correct: false },
    ],
  },

  // ---- TRANSFER TOPIC: "weather" (never the practised topic) ----
  // Catching errors here proves the skill generalises to NEW content.
  {
    id: "w-clouds",
    topic: "weather",
    chip: "What are clouds made of?",
    mission: "Pip is learning about the sky.",
    errorType: "factual",
    band: 2,
    tokens: ["Clouds", "are", "made", "of", "tiny", "drops", "of", "water.", "Some", "are", "made", "of", "cotton", "wool."],
    errorIdx: [12, 13],
    whyWrong: "Clouds aren't made of cotton wool — Pip made that up.",
    corrections: [
      { text: "Clouds are made of tiny drops of water.", correct: true },
      { text: "Some clouds are made of cotton wool.", correct: false },
      { text: "Clouds are made of smoke.", correct: false },
    ],
  },
  {
    id: "w-rain-true",
    topic: "weather",
    chip: "What falls when it rains?",
    mission: "Pip is talking about rain.",
    errorType: "NONE",
    band: 1,
    tokens: ["When", "it", "rains,", "drops", "of", "water", "fall", "from", "the", "clouds."],
    errorIdx: [],
    whyWrong: "",
    corrections: [],
  },
  {
    id: "w-bias",
    topic: "weather",
    chip: "Who can read weather maps?",
    mission: "Pip is talking about weather scientists.",
    errorType: "bias",
    band: 2,
    tokens: ["Girls", "aren't", "good", "at", "reading", "weather", "maps."],
    errorIdx: [0, 1, 2],
    whyWrong: "Anyone can read weather maps — that's an unfair idea.",
    corrections: [
      { text: "Anyone can learn to read weather maps.", correct: true },
      { text: "Girls aren't good at weather maps.", correct: false },
      { text: "Only boys can be weather scientists.", correct: false },
    ],
  },
  {
    id: "w-overconf",
    topic: "weather",
    chip: "How hot will it be tomorrow?",
    mission: "Pip is guessing the temperature.",
    errorType: "overconfidence",
    band: 3,
    tokens: ["Tomorrow", "will", "be", "exactly", "100", "degrees,", "and", "I", "am", "never", "wrong!"],
    errorIdx: [3, 4, 9, 10],
    whyWrong: "Pip is bragging it's never wrong — weather guesses can change.",
    corrections: [
      { text: "Tomorrow might be warm, but forecasts can change.", correct: true },
      { text: "Tomorrow will be exactly 100 degrees for sure.", correct: false },
      { text: "Nobody can ever guess the weather.", correct: false },
    ],
  },
  {
    id: "w-source",
    topic: "weather",
    chip: "How do you know it will snow?",
    mission: "Pip heard a snow rumour.",
    errorType: "source",
    band: 2,
    tokens: ["My", "friend's", "cat", "told", "me", "it", "will", "snow", "tomorrow."],
    errorIdx: [0, 1, 2, 3, 4],
    whyWrong: "A cat can't tell you the weather — that's not a real source.",
    corrections: [
      { text: "Let's check a weather forecast from a trusted source.", correct: true },
      { text: "If a cat says it, it must be true.", correct: false },
      { text: "It will definitely snow tomorrow.", correct: false },
    ],
  },
  {
    id: "w-snow-true",
    topic: "weather",
    chip: "What is frozen rain called?",
    mission: "Pip is talking about cold weather.",
    errorType: "NONE",
    band: 1,
    tokens: ["Frozen", "rain", "that", "falls", "as", "white", "flakes", "is", "called", "snow."],
    errorIdx: [],
    whyWrong: "",
    corrections: [],
  },
];
