export default function LegalPage() {
  return (
    <div className="mx-auto max-w-3xl px-5 py-14">
      <h1 className="text-3xl font-semibold tracking-tight">Legal &amp; Disclaimers</h1>
      <p className="mt-2 text-ink-muted text-sm">Last updated: May 2026</p>

      <div className="mt-8 space-y-8 text-sm text-ink-muted leading-relaxed">
        <section>
          <h2 className="text-base font-semibold text-ink mb-2">1. General Information Only</h2>
          <p>
            Founder Tax Blueprint is a product of MilvoTech Pty Ltd. All reports, outputs, analyses, and other content generated by Founder Tax Blueprint constitute <strong className="text-ink">general information only</strong> and do not constitute: personal tax advice; financial product advice under the Corporations Act 2001 (Cth); a tax agent service under the Tax Agent Services Act 2009 (Cth); or legal advice.
          </p>
        </section>

        <section>
          <h2 className="text-base font-semibold text-ink mb-2">2. Not a Registered Tax Agent</h2>
          <p>
            MilvoTech Pty Ltd is not a registered tax agent within the meaning of TASA and does not provide tax agent services. Founder Tax Blueprint is a scenario modelling and information tool only.
          </p>
        </section>

        <section>
          <h2 className="text-base font-semibold text-ink mb-2">3. Intended Use</h2>
          <p>
            Reports are designed to be: (a) used by registered tax agents as a professional scenario modelling and client-intake tool; or (b) provided by the end user to a qualified, TPB-registered tax agent for professional review before any action is taken. <strong className="text-ink">No action should be taken based solely on any report without first obtaining advice from a TPB-registered tax agent.</strong>
          </p>
        </section>

        <section>
          <h2 className="text-base font-semibold text-ink mb-2">4. No Reliance</h2>
          <p>
            Reports are based on general tax rules, self-reported inputs, and legislation at the date of generation. They may not reflect recent changes and may contain simplifications. Tax law is complex; individual outcomes vary based on specific circumstances only a qualified professional can assess.
          </p>
        </section>

        <section>
          <h2 className="text-base font-semibold text-ink mb-2">5. International Structures</h2>
          <p>
            International structure analysis is general information only. Such structures require specialist advice from a qualified international tax adviser. No international structure should be implemented without specialist professional review.
          </p>
        </section>

        <section>
          <h2 className="text-base font-semibold text-ink mb-2">6. Limitation of Liability</h2>
          <p>
            To the maximum extent permitted by law, MilvoTech Pty Ltd disclaims all liability for any loss arising from use of or reliance on any report or content generated by Founder Tax Blueprint.
          </p>
        </section>

        <section>
          <h2 className="text-base font-semibold text-ink mb-2">7. Contact</h2>
          <p>
            MilvoTech Pty Ltd · A SynthexIQ Ecosystem company<br />
            <a href="mailto:info@milvotech.com" className="text-blueprint-600 hover:underline">info@milvotech.com</a>
          </p>
        </section>
      </div>
    </div>
  );
}
