import Link from "next/link";
import { Logo } from "./Logo";

export function SiteFooter() {
  return (
    <footer className="mt-16 border-t border-black/5 bg-white">
      <div className="mx-auto max-w-6xl px-5 py-6 text-xs text-ink-muted">
        <div className="flex flex-col md:flex-row gap-4 md:items-center md:justify-between mb-4">
          <div className="flex items-center gap-3">
            <Logo />
          </div>
          <div className="flex flex-wrap gap-5 text-sm">
            <Link href="/#how" className="hover:text-ink">How it works</Link>
            <Link href="/#report" className="hover:text-ink">The report</Link>
            <Link href="/legal" className="hover:text-ink">Legal & disclaimers</Link>
            <a href="mailto:info@milvotech.com" className="hover:text-ink">Contact</a>
          </div>
          <div className="text-sm">© {new Date().getFullYear()} MilvoTech Pty Ltd</div>
        </div>
        <p className="leading-relaxed border-t border-black/5 pt-4">
          <strong>General information only.</strong> Reports generated by Founder Tax Blueprint constitute general information only and do not constitute personal tax advice, financial advice, or a tax agent service within the meaning of the Tax Agent Services Act 2009 (Cth). MilvoTech Pty Ltd is not a registered tax agent. Reports are designed to be used by registered tax agents or provided to a qualified accountant for professional review before any action is taken.
        </p>
      </div>
    </footer>
  );
}
